apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  otel-config.yaml: |
    {{- tpl (include "opentelemetry-collector.config" .) . | nindent 4 }}
