{{- $pw := (include "syncthing.password" .) | fromJson }}
{{- if and $pw.create $pw.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pw.name }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  PASSWORD: {{ .Values.env.PASSWORD | default (randAlphaNum 40) }}
{{- end }}
