apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "showcase-yourself.fullname" . }}-frontend
  labels:
    {{- include "showcase-yourself.componentLabels" (dict "context" . "component" "frontend") | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "release") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "showcase-yourself.componentSelectorLabels" (dict "context" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "showcase-yourself.componentSelectorLabels" (dict "context" . "component" "frontend") | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "showcase-yourself.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          {{- if .Values.frontend.content }}
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html/showcase.json
              subPath: showcase.json
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- if .Values.frontend.content }}
      volumes:
        - name: content
          configMap:
            name: {{ include "showcase-yourself.fullname" . }}-frontend-content
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
