{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "forgejo.fullname" . }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "forgejo.fullname" . }}-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-password
    remoteRef:
      key: {{ .Values.externalSecrets.keys.databasePassword }}
  - secretKey: runner-token
    remoteRef:
      key: {{ .Values.externalSecrets.keys.runnerToken }}
  {{- if .Values.mirrorCronJob.enabled }}
  - secretKey: github-token
    remoteRef:
      key: {{ .Values.externalSecrets.keys.githubToken }}
  - secretKey: forgejo-token
    remoteRef:
      key: {{ .Values.externalSecrets.keys.forgejoToken }}
  {{- end }}
{{- end }}
