apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgejo.fullname" . }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  database-password: {{ .Values.secrets.databasePassword | quote }}
  runner-token: {{ .Values.secrets.runnerToken | quote }}
