apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgejo.fullname" . }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "ingress" "annotations" .Values.service.annotations) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "forgejo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgejo.fullname" . }}-ssh
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
  {{- $sshAnnotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "ingress" "annotations" .Values.service.ssh.annotations) }}
  {{- if $sshAnnotations }}
  annotations:
    {{- $sshAnnotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.ssh.type }}
  ports:
    - port: {{ .Values.service.ssh.port }}
      targetPort: ssh
      {{- if (and (eq .Values.service.ssh.type "NodePort") .Values.service.ssh.nodePort) }}
      nodePort: {{ .Values.service.ssh.nodePort }}
      {{- end }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "forgejo.selectorLabels" . | nindent 4 }}
