apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgejo.fullname" . }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "forgejo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgejo.fullname" . }}-ssh
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.ssh.type }}
  ports:
    - port: {{ .Values.service.ssh.port }}
      targetPort: ssh
      {{- if (and (eq .Values.service.ssh.type "NodePort") .Values.service.ssh.nodePort) }}
      nodePort: {{ .Values.service.ssh.nodePort }}
      {{- end }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "forgejo.selectorLabels" . | nindent 4 }}
