apiVersion: v2
name: forgejo
description: A Helm chart for Forgejo, a self-hosted lightweight software forge.
type: application
version: 0.1.1
appVersion: '9'
keywords:
- forgejo
- git
- devops
home: https://forgejo.org/
sources:
- https://codeberg.org/forgejo/forgejo
- https://github.com/PatNei/GITHUB2FORGEJO
dependencies:
- name: postgres
  alias: postgresql
  version: 0.1.18
  repository: file://../postgres
  condition: postgresql.enabled
maintainers:
- name: mbround18
