apiVersion: v2
name: keygen
description: A Helm chart for Keygen, a self-hosted software licensing and distribution
  API.
type: application
version: 0.1.3
appVersion: latest
icon: https://keygen.sh/favicon.ico
keywords:
- keygen
- licensing
- software-licensing
home: https://keygen.sh/
sources:
- https://github.com/keygen-sh/keygen-api
dependencies:
- name: postgres
  version: 0.1.30
  repository: file://../postgres
  condition: postgres.enabled
- name: redis
  version: 0.1.0
  repository: file://../redis
  condition: redis.enabled
- name: gitops-tools
  version: 0.1.1
  repository: file://../gitops-tools
maintainers:
- name: mbround18
