apiVersion: v2
name: opentelemetry-collector
description: A Helm chart for Kubernetes
icon: https://github.com/cncf/artwork/blob/main/projects/opentelemetry/icon/color/opentelemetry-icon-color.svg
type: application
version: 0.1.8
appVersion: 0.150.1-386
dependencies:
- name: gitops-tools
  version: 0.1.1
  repository: https://mbround18.github.io/helm-charts
