{{- if .Values.secrets.create }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "keygen.secretsName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keygen.secretsName" . }}
  labels:
    {{- include "keygen.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
stringData:
  {{- if $secret }}
  SECRET_KEY_BASE: {{ index $secret.data "SECRET_KEY_BASE" | b64dec }}
  ENCRYPTION_DETERMINISTIC_KEY: {{ index $secret.data "ENCRYPTION_DETERMINISTIC_KEY" | b64dec }}
  ENCRYPTION_PRIMARY_KEY: {{ index $secret.data "ENCRYPTION_PRIMARY_KEY" | b64dec }}
  ENCRYPTION_KEY_DERIVATION_SALT: {{ index $secret.data "ENCRYPTION_KEY_DERIVATION_SALT" | b64dec }}
  KEYGEN_ACCOUNT_ID: {{ index $secret.data "KEYGEN_ACCOUNT_ID" | b64dec }}
  {{- else }}
  SECRET_KEY_BASE: {{ randAlphaNum 128 | quote }}
  ENCRYPTION_DETERMINISTIC_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  ENCRYPTION_PRIMARY_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  ENCRYPTION_KEY_DERIVATION_SALT: {{ randAlphaNum 32 | b64enc | quote }}
  KEYGEN_ACCOUNT_ID: {{ .Values.keygen.accountId | default uuidv4 | quote }}
  {{- end }}
{{- end }}
