apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name | default "pvc-scaler-role" }}
rules:
  - apiGroups: [""]
    resources:
      - "clusterkopfpeerings"
      - "events"
    verbs:
      - "create"
  - apiGroups: [""]
    resources:
      - "clusterkopfpeerings"
      - "persistentvolumeclaims"
      - "events"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "deployments/scale"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
