apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "ingress" "annotations" .Values.service.annotations) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  {{- if .Values.service.managementPort.enabled }}
  - name: management
    port: {{ .Values.service.managementPort.port }}
    targetPort: {{ .Values.service.managementPort.targetPort }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
