apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}-headless
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "release") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.endpoint.gamePort }}
      targetPort: game-tcp
      protocol: TCP
      name: game-tcp
  selector:
    {{- include "palworld.selectorLabels" . | nindent 4 }}
