{{- $pvcs := .Values.pvcs }}
{{- if not (index .Values "backup-job" "enabled") }}
{{- $pvcs = omit $pvcs "backups" }}
{{- end }}
{{- range $pvcs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
      app: {{ include "palworld.name" $ }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" $ "phase" "foundation") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: {{ .size }}
    storageClassName: {{ $.Values.storageClassName | default "longhorn" }}
{{- end }}
