---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcs.saved.name}}
  labels:
      app: {{ include "palworld.name" . }}
  {{- $savedAnnotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $savedAnnotations }}
  annotations:
    {{- $savedAnnotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: {{ .Values.pvcs.saved.size }}
    storageClassName: {{ .Values.storageClassName | default "longhorn" }}
---
{{- if .Values.backups.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcs.backups.name }}
  labels:
      app: {{ include "palworld.name" . }}
  {{- $backupsAnnotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $backupsAnnotations }}
  annotations:
    {{- $backupsAnnotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: {{ .Values.pvcs.backups.size }}
    storageClassName: {{ .Values.storageClassName | default "longhorn" }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcs.server.name }}
  labels:
      app: {{ include "palworld.name" . }}
  {{- $serverAnnotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $serverAnnotations }}
  annotations:
    {{- $serverAnnotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: {{ .Values.pvcs.server.size }}
    storageClassName: {{ .Values.storageClassName | default "longhorn" }}
