{{- if not .Values.agones.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "ingress" "annotations" (dict "argocd.argoproj.io/sync-options" "ServerSideApply=true")) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  externalIPs:
    - {{ .Values.endpoint.externalIP }}
  ports:
    {{- range list "query" "game" }}
    {{- $portName := . }}
    {{- $portValue := index $.Values.endpoint (printf "%sPort" $portName) }}
    {{- $nodePortValue := index $.Values.endpoint (printf "%sNodePort" $portName) }}
    {{- range list "TCP" "UDP" }}
      - port: {{ $portValue }}
        targetPort: {{ printf "%s-%s" $portName (lower .) }}
        protocol: {{ . }}
        name: {{ printf "%s-%s" $portName (lower .) }}
        {{- if $nodePortValue }}
        nodePort: {{ $nodePortValue }}
        {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "palworld.selectorLabels" . | nindent 4 }}
{{- end }}
