{{- if not .Values.agones.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "release") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "palworld.fullname" . }}-headless
  {{- $pvcs := .Values.pvcs }}
  {{- if not (index .Values "backup-job" "enabled") }}
  {{- $pvcs = omit $pvcs "backups" }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "palworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "palworld.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "palworld.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.initContainer.enabled }}
      initContainers:
        - name: {{ .Chart.Name }}-installer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          resources:
            {{- toYaml .Values.initContainer.resources | nindent 12 }}
          volumeMounts:
          {{- range $pvcs }}
            - name: {{ .name }}
              mountPath: {{ .path }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.environment }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range list "query" "game" }}
            {{- $portName := . }}
            {{- $portValue := index $.Values.endpoint (printf "%sPort" $portName) }}
            {{- range list "TCP" "UDP" }}
            - name: {{ printf "%s-%s" $portName (lower .) }}
              containerPort: {{ $portValue }}
              protocol: {{ . }}
            {{- end }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: game-tcp
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: game-tcp
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- range $pvcs }}
            - name: {{ .name }}
              mountPath: {{ .path }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- $combinedVolumes := .Values.volumes }}
      {{- range $pvcs }}
      {{- $newVolume := dict "name" .name "persistentVolumeClaim" (dict "claimName" .name) }}
      {{- $combinedVolumes = append $combinedVolumes $newVolume }}
      {{- end }}
      volumes:
        {{- toYaml $combinedVolumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
