apiVersion: v1
kind: Service
metadata:
  name: {{ include "audiobookshelf.fullname" . }}
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "ingress") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "audiobookshelf.selectorLabels" . | nindent 4 }}
