apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openobserve.fullname" . }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
data:
  ZO_LOCAL_MODE: {{ .Values.config.localMode | quote }}
  RUST_LOG: {{ .Values.config.logLevel | quote }}
  ZO_TELEMETRY_ENABLED: {{ .Values.config.telemetry | quote }}
  ZO_S3_BUCKET_NAME: {{ .Values.config.s3.bucket | quote }}
  ZO_S3_SERVER_URL: {{ .Values.config.s3.serverUrl | quote }}
  ZO_S3_REGION: {{ .Values.config.s3.region | quote }}
  ZO_MEMORY_CACHE_MAX_SIZE: {{ include "openobserve.memoryCacheMaxSize" . | quote }}
