name: "Setup Python"
description: "Composite action: installs Python (default 3.14) and pip packages (default: astral)."
runs:
  using: "composite"
  steps:
      - name: Install yq
        uses: mbround18/gh-reusable/actions/install-cli@v0.0.6
        with:
          repository: "mikefarah/yq"
          version: "latest"
          asset: "yq_linux_amd64"
          override-name: "yq"

      - name: Setup Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
