apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "database") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    {{- include "mongo.selectorLabels" . | nindent 4 }}
