apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.pvc.name }}
  labels:
    app: {{ include "hytale.name" . }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.storageClassName | default "longhorn" }}
