apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "foundryvtt.fullname" . }}
  labels:
    {{- include "foundryvtt.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.network.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "foundryvtt.fullname" . }}
                port:
                  number: 80
  {{- if .Values.network.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.network.host }}
      secretName: {{ .Values.network.tls.credentialName }}
  {{- end }}
