{{- if and .Values.ingress.enabled (not (index .Values "istio-ingress" "enabled")) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "foundryvtt.fullname" . }}
  labels:
    {{- include "foundryvtt.labels" . | nindent 4 }}
  {{- $extraAnnotations := dict "nginx.ingress.kubernetes.io/force-ssl-redirect" "true" "nginx.ingress.kubernetes.io/proxy-body-size" "100m" }}
  {{- range $key, $value := .Values.ingress.annotations }}
  {{- $_ := set $extraAnnotations $key $value }}
  {{- end }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "ingress" "annotations" $extraAnnotations) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "foundryvtt.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
  {{- if .Values.network.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.network.host }}
      secretName: {{ .Values.network.tls.credentialName }}
  {{- end }}
{{- end }}
