apiVersion: v2
name: foundryvtt
description: A Helm chart for Foundry Virtual Tabletop
type: application
version: 0.1.2
appVersion: '1.0'
home: https://foundryvtt.com/
keywords:
- foundry
- foundryvtt
- tabletop
- gaming
maintainers:
- name: mbround18
