apiVersion: v2
name: meilisearch
description: A Helm chart for Meilisearch
type: application
version: 0.1.19
appVersion: v1.30.0
dependencies:
  - name: istio-ingress
    version: 0.1.4
    repository: https://mbround18.github.io/helm-charts
    condition: istio-ingress.enabled
