apiVersion: v2
name: vaultwarden
description: Helm chart for Vaultwarden with safety-first persistent storage defaults
type: application
version: 0.1.2
appVersion: 1.35.4
dependencies:
  - name: gitops-tools
    version: 0.1.0
    repository: file://../gitops-tools
