{{- if not .Values.auth.existingSecret }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.generatedSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.generatedSecretName }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
stringData:
  {{- if $secret }}
  {{ .Values.auth.accessKeyKey }}: {{ index $secret.data .Values.auth.accessKeyKey | b64dec }}
  {{ .Values.auth.secretKeyKey }}: {{ index $secret.data .Values.auth.secretKeyKey | b64dec }}
  {{- else }}
  {{ .Values.auth.accessKeyKey }}: {{ randAlphaNum 20 | quote }}
  {{ .Values.auth.secretKeyKey }}: {{ randAlphaNum 48 | quote }}
  {{- end }}
{{- end }}
