apiVersion: v1
kind: Service
metadata:
  name: {{ include "vtt-maps-portal.fullname" . }}
  labels:
    {{- include "vtt-maps-portal.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "ingress") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vtt-maps-portal.selectorLabels" . | nindent 4 }}
