{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-hub.fullname" . }}-db-conn
  labels:
    {{- include "helm-hub.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgres://%s:%s@%s.%s.svc.cluster.local:%d/%s" (include "helm-hub.databaseUser" .) (.Values.postgres.auth.password | default "postgres") (include "helm-hub.databaseHost" .) .Release.Namespace 5432 (include "helm-hub.databaseName" .) | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | default (randAlphaNum 32) | quote }}
{{- end }}

{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-hub.fullname" . }}
  labels:
    {{- include "helm-hub.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
