{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "changedetection-io.fullname" . }}
  labels:
    {{- include "changedetection-io.labels" . | nindent 4 }}
  {{- $annotations := include "gitops-tools.argocd.annotations" (dict "context" . "phase" "foundation") }}
  {{- with $annotations }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
